#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env.Append(LIBPATH=["#modules/gdextension/addons/godot-rapier2d/bin/libgodot_rapier.macos.framework"])
env.Append(LIBPATH=["#modules/gdextension/addons/godot_sandbox/bin/libgodot_riscv.macos.template_debug.arm64.framework"])
env.Append(LIBPATH=["#modules/gdextension/addons"])
#env.Append(LIBS=["libgodot_rapier.macos.a"])
env.Append(LIBS=["libgodot_riscv.macos.template_debug.arm64"])
env.Append(LIBS=["libgodot-cpp.macos.template_debug.arm64.a"])
env_gdextension = env_modules.Clone()

env_gdextension.add_source_files(env.modules_sources, "*.cpp")
